"""Add game_user Association Table

Revision ID: 3e7ed776a093
Revises: 775be82ad305
Create Date: 2023-09-01 17:26:59.270267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7ed776a093'
down_revision = '775be82ad305'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
